import argparse
import pandas as pd
import os


def join_dataframes(dataframes, suffixes, output_dir, github_commit):
    log_file_path = os.path.join(output_dir, 'merge_log.txt')
    with open(log_file_path, 'w') as log_file:
        log_file.write(f'GitHub Commit: {github_commit}\n')

        # Load and rename columns
        dfs = []
        for path, suffix in zip(dataframes, suffixes):
            df = pd.read_csv(path)
            original_columns = df.columns
            df = df.add_suffix(f'_{suffix}')
            df = df.rename(columns={f'variant_{suffix}': 'variant'})
            dfs.append(df)
            log_file.write(f"Loaded '{path}' with suffix '{suffix}'\n")
            log_file.write(f"Original columns: {list(original_columns)}\n")
            log_file.write(f"Renamed columns: {list(df.columns)}\n\n")

        # Merge on the 'variant' column
        merged_df = dfs[0]
        missing_counts = {}
        for df, suffix in zip(dfs[1:], suffixes[1:]):
            initial_count = len(merged_df)
            merged_df = merged_df.merge(df, on='variant', how='inner')
            overlap_count = len(merged_df)
            missing_counts[suffix] = initial_count - overlap_count

        # Logging overlapping and missing variants
        total_overlap = len(merged_df)
        log_file.write(f"Total overlapping variants: {total_overlap}\n")
        for suffix, count in missing_counts.items():
            log_file.write(f"Variants missing from '{suffix}': {count}\n")

        # Save the merged dataframe
        output_path = os.path.join(output_dir, 'final_energies_df.csv')
        merged_df.to_csv(output_path, index=False)
        log_file.write(f"Final merged dataframe saved to '{output_path}'\n")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Join multiple dataframes generated by metl sim simulations.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        fromfile_prefix_chars="@"
    )
    parser.add_argument("--dataframes", nargs='+', required=True, help="Paths to the dataframes to join.")
    parser.add_argument("--suffixes", nargs='+', required=True, help="Suffixes corresponding to each dataframe.")
    parser.add_argument("--output_dir", type=str, required=True, help="Directory to save the final merged dataframe and log file.")
    parser.add_argument("--github_commit", type=str, required=True, help="GitHub commit identifier.")

    args = parser.parse_args()

    if len(args.dataframes) != len(args.suffixes):
        raise ValueError("The number of dataframes and suffixes must match.")

    os.makedirs(args.output_dir, exist_ok=True)
    join_dataframes(args.dataframes, args.suffixes, args.output_dir, args.github_commit)




