import argparse
import pandas as pd
import os

def join_dataframes(dataframes, suffixes, output_dir, github_commit,file,remove_zero_variance):
    '''

    :param dataframes: list of paths to the directory containing the necessary dataframes which come from a metl-sim run
    :param suffixes: what suffix to label each run with
    :param output_dir: output directory to save all new files
    :param github_commit: github commit this code was run with
    :param file: between -  ['energies_df.csv','hparams_df.csv','jobs_df.csv']
    :param remove_zero_variance: remove columnes which have zero variants [True, False]
    :return:
    '''


    log_file_path = os.path.join(output_dir, 'merge_log.txt')

    with open(log_file_path, 'w') as log_file:


        def log_and_print(message):
            """Helper function to log and print messages."""
            print(message)
            log_file.write(message + '\n')

        log_and_print(f"File to merge: {file}")

        log_and_print(f'GitHub Commit: {github_commit}')

        # Load and rename columns
        dfs = []
        for path, suffix in zip(dataframes, suffixes):

            df = pd.read_csv(os.path.join(path,'processed_run',file))
            original_columns = df.columns

            if suffix=='relax':
                df = df.add_suffix(f'')
                df = df.rename(columns={f'variant': 'variant'})
            else:
                df = df.add_suffix(f'_{suffix}')
                df = df.rename(columns={f'variant_{suffix}': 'variant'})
            dfs.append(df)

            log_and_print(f"\nLoaded '{path}' with suffix '{suffix}'")
            log_and_print(f"Original columns: {list(original_columns)}")
            log_and_print(f"Renamed columns: {list(df.columns)}\n")

        # Merge on the 'variant' column
        merged_df = dfs[0]
        missing_counts = {}
        for df, suffix in zip(dfs[1:], suffixes[1:]):

            merged_df = merged_df.merge(df, on='variant', how='inner')



        # Logging overlapping and missing variants
        total_overlap = len(merged_df)

        log_and_print(f"\nTotal overlapping variants: {total_overlap} \n"
                      f"Note: this includes extra variants from duplicates in some libraries")

        for df, suffix in zip(dfs, suffixes):

            initial_count = len(df)
            count = initial_count - total_overlap
            log_and_print(f"Variants missing from '{suffix}': {count}")

        # Remove columns with zero variance
        if remove_zero_variance:

            zero_variance_columns = merged_df.loc[:, merged_df.nunique() <= 1].columns.tolist()
            if zero_variance_columns:
                zero_variance_columns = [item for item in zero_variance_columns if not item.startswith('pdb_fn')]
                log_and_print(f"\nRemoving columns with zero variance: {zero_variance_columns}")
                merged_df = merged_df.drop(columns=zero_variance_columns)
            else:
                log_and_print("\nNo columns with zero variance to remove.")
        else:
            log_and_print("\nSkipping removing columns with zero variance due to user specification.")


        # Save the merged dataframe
        output_path = os.path.join(output_dir,'processed_run', 'energies_df.csv')
        merged_df.to_csv(output_path, index=False)
        log_and_print(f"\nFinal merged dataframe saved to '{output_path}'")
        log_and_print(f"Log file saved to '{log_file_path}'")


def concat_dataframes(paths,file,output_dir):
    dfs=[]
    for path in paths:
        df= pd.read_csv(os.path.join(path,'processed_run',file))
        dfs.append(df)

    df_final = pd.concat(dfs)


    df_final.to_csv(os.path.join(output_dir,'processed_run',file),index=False)

if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description="Join multiple dataframes generated by metl sim simulations.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        fromfile_prefix_chars="@"
    )
    parser.add_argument("--dataframes", nargs='+', required=True, help="Paths to the directories of the dataframes to join.")
    parser.add_argument("--suffixes", nargs='+', required=True, help="Suffixes corresponding to each dataframe.")
    parser.add_argument("--output_dir", type=str, required=True, help="Directory to save the final merged dataframe and log file.")
    parser.add_argument("--github_commit", type=str, required=True, help="GitHub commit identifier.")
    args = parser.parse_args()

    if len(args.dataframes) != len(args.suffixes):
        raise ValueError("The number of dataframes and suffixes must match.")

    os.makedirs(args.output_dir, exist_ok=True)

    os.makedirs(os.path.join(args.output_dir,'processed_run'),exist_ok=True)
    os.makedirs(os.path.join(args.output_dir, 'output','energize_outputs'), exist_ok=True)

    for file in ['hparams_df.csv','jobs_df.csv']:
        concat_dataframes(args.dataframes,file, args.output_dir)


    join_dataframes(args.dataframes, args.suffixes, args.output_dir, args.github_commit, file='energies_df.csv',
                    remove_zero_variance=True)

