CREATE TABLE IF NOT EXISTS `variant` (
    `pdb_fn` TEXT NOT NULL,
    `mutations` TEXT NOT NULL,
    `job_uuid` TEXT NOT NULL,
    `start_time` TEXT,
    `run_time` INTEGER,
    `mutate_run_time` INTEGER,
    `dock_run_time` INTEGER,
    `total_score` REAL,
    `Grid_score` REAL,
    `Transform_accept_ratio` REAL,
    `angle_constraint` REAL,
    `atom_pair_constraint` REAL,
    `chainbreak` REAL,
    `classic_grid_X` REAL,
    `coordinate_constraint` REAL,
    `dihedral_constraint` REAL,
    `dslf_ca_dih` REAL,
    `dslf_cs_ang` REAL,
    `dslf_ss_dih` REAL,
    `dslf_ss_dst` REAL,
    `fa_atr` REAL,
    `fa_dun` REAL,
    `fa_elec` REAL,
    `fa_pair` REAL,
    `fa_rep` REAL,
    `fa_sol` REAL,
    `hbond_bb_sc` REAL,
    `hbond_lr_bb` REAL,
    `hbond_sc` REAL,
    `hbond_sr_bb` REAL,
    `if_X_angle_constraint` REAL,
    `if_X_atom_pair_constraint` REAL,
    `if_X_chainbreak` REAL,
    `if_X_coordinate_constraint` REAL,
    `if_X_dihedral_constraint` REAL,
    `if_X_dslf_ca_dih` REAL,
    `if_X_dslf_cs_ang` REAL,
    `if_X_dslf_ss_dih` REAL,
    `if_X_dslf_ss_dst` REAL,
    `if_X_fa_atr` REAL,
    `if_X_fa_dun` REAL,
    `if_X_fa_elec` REAL,
    `if_X_fa_pair` REAL,
    `if_X_fa_rep` REAL,
    `if_X_fa_sol` REAL,
    `if_X_hbond_bb_sc` REAL,
    `if_X_hbond_lr_bb` REAL,
    `if_X_hbond_sc` REAL,
    `if_X_hbond_sr_bb` REAL,
    `if_X_omega` REAL,
    `if_X_p_aa_pp` REAL,
    `if_X_pro_close` REAL,
    `if_X_ref` REAL,
    `interface_delta_X` REAL,
    `ligand_is_touching_X` REAL,
    `omega` REAL,
    `p_aa_pp` REAL,
    `pro_close` REAL,
    `ref` REAL,
    `total_score_X` REAL,

    PRIMARY KEY (`pdb_fn`, `mutations`, `job_uuid`)

    FOREIGN KEY (`pdb_fn`) REFERENCES pdb_file(`pdb_fn`),
    FOREIGN KEY (`job_uuid`) REFERENCES job(`uuid`));

CREATE INDEX mutations_index ON variant(mutations);
CREATE INDEX pdb_fn_index ON variant(pdb_fn);

CREATE TABLE IF NOT EXISTS  `pdb_file` (
    `pdb_fn` TEXT,
    `aa_sequence` TEXT,
    `seq_len` INTEGER,
    PRIMARY KEY (`pdb_fn`));

CREATE TABLE IF NOT EXISTS  `job` (
    `uuid` TEXT,
    `cluster` TEXT,
    `process` TEXT,
    `hostname` TEXT,
    `github_tag` TEXT,
    `script_start_time` TEXT,
    `hp_mutate_default_max_cycles` INTEGER,
    `hp_relax_repeats` INTEGER,
    `hp_relax_nstruct` INTEGER,
    `hp_relax_distance` REAL,
    PRIMARY KEY (`uuid`));