universe = container
+WantFlocking = true
+WantGlideIn = true

log = output/condor_logs/rosetta_$(Cluster)_$(Process).log
error = output/condor_logs/rosetta_$(Cluster)_$(Process).err
output = output/condor_logs/rosetta_$(Cluster)_$(Process).out

# need to do this becasue of some obscure error when using max_default_idle
container_image = metl_sim.sif
transfer_container = False


# rosetta provides the precompiled 64bit binaries for linux
# has_avx is included because I think I ran into avx-related errors in the past
# (GlideIN_Site =!= "FNAL") is meant to exclude the FNAL site because of problems
requirements = (Arch == "X86_64") && (has_avx == true) && (OpSys=="LINUX") && (GlideIN_Site =!= "FNAL")
executable = run.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = run.sh, code.tar.gz,  args/$(Process).txt, osdf:///chtc/staging/bcjohnson7/metl_sim.sif, energize_args.txt, {transfer_input_files}
transfer_output_files = output

request_cpus = 1
request_memory = 2GB
retry_request_memory = 3GB
request_disk = 20GB

environment = "CLUSTER=$(Cluster) PROCESS=$(Process) RUNNINGON=$$(Name) GITHUB_TAG=$ENV(GITHUB_TAG) PYSCRIPT=$ENV(PYSCRIPT)"

# when submitting more than 10k jobs this will prevent the scheduler from getting overloaded
max_idle = 1000

# set it so jobs that fail will go on hold
on_exit_hold = (ExitCode =!= 0)
on_exit_hold_subcode = 1
on_exit_hold_reason = "Nonzero exit-code"

# periodically release failed jobs up to 5 times the hold reason code will be 3, and the subcode (set above) will be 1
# auto release jobs that fail to transfer files from squid (hold reason code 12, subcode 0)
periodic_release = ((NumJobStarts < 5) && (HoldReasonCode == 13) && ((CurrentTime - EnteredCurrentStatus) > 600)) || ((NumJobStarts < 5) && (HoldReasonCode == 3) && (HoldReasonSubCode == 1) && ( (CurrentTime - EnteredCurrentStatus) > 600))

queue $ENV(NUM_JOBS)